### ISSUE TITLE
Bug during finetuning training

### ISSUE THREAD

**Issue by asusdisciple** [yl4579/StyleTTS2#104]
I am currently running a training approach on 4xV100 with 32 GB. I am using a dataset in the style of LJSpeech and the the
finetuning training script. When I use a `batch size of 8,` I get OOM errors at some point. But when I reduce the `batch size to 4`
this error appears right in the beginning. Do you have an idea why changing the batch size to 4 could lead to this error? 

```
Traceback (most recent call last):
  File "/raid/me/projects/StyleTTS2/train_finetune.py", line 714, in <module>
    main()
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/train_finetune.py", line 396, in main
    y_rec_gt_pred = model.decoder(en, F0_real, N_real, s)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/Modules/hifigan.py", line 458, in forward
    F0 = self.F0_conv(F0_curve.unsqueeze(1))
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/raid/me/projects/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [1, 1, 3], expected input[1, 284, 1] to have 1 channels, but got 284 channels instead

```

Changing the batch size to 3 results in this error in the last line:

`RuntimeError: Given groups=1, weight of size [1, 1, 3], expected input[1, 221, 1] to have 1 channels, but got 221 channels instead`

Apparently there is an issue with the expected input?

**Comment by devidw** [comment]
I would double-check that all you dataset examples have a minimum length of one second.

**Comment by stevenhillis** [comment]
Your effective batch size of 4 gets spread across 4 machines: local batch size of 1. I'd bet there's an indiscriminate squeeze() somewhere that's eroding your batch dimension.

**Comment by yl4579** [comment]
@stevenhillis Yeah the code is honestly very funky with a bunch of hardcoding and brute solutions to dimensions so it only supports batch size smaller than 2. 

@asusdisciple I’d recommend you lower `max_len` to fit batch size 8 to 4 GPUs so each GPU has at least 2 samples, otherwise it won’t work.

**Comment by asusdisciple** [comment]
already decreased hop size and max len. I definately have no samples below 3 seconds, but some are about 30 seconds long, probably its because of that. By the way I wondered why the memory consumption is so high? with a batch size of 8 this would means 2 files per gpu. I mean I know wav-lm has a memory complexity of n^4 but I am still wondering about this.

**Comment by yl4579** [comment]
@asusdisciple If the problem happens after `joint_epoch`, you should also lower the SLM adversarial training `min_len`  and `max_len` under `slmadv_params`.

**Comment by dabsdamoon-h** [comment]
@stevenhillis @yl4579 FYI, you might figure out it already and not sure whether it's all of them, but just let you know that squeeze() code occurs at slmadv.py so might want to do something like below:



    def forward(
            self,
            iters,
            y_rec_gt,
            y_rec_gt_pred,
            waves,
            mel_input_length,
            ref_text,
            ref_lengths,
            use_ind,
            s_trg,
            ref_s=None
        ):

        text_mask = length_to_mask(ref_lengths).to(ref_text.device)
        bert_dur = self.model.bert(ref_text, attention_mask=(~text_mask).int())
        if self.multilingual:
            bert_dur = bert_dur.last_hidden_state
        d_en = self.model.bert_encoder(bert_dur).transpose(-1, -2) 
        
        if use_ind and np.random.rand() < 0.5:
            s_preds = s_trg
        else:
            num_steps = np.random.randint(3, 5)
            if ref_s is not None:
                s_preds = self.sampler(
                    noise = torch.randn_like(s_trg).unsqueeze(1).to(ref_text.device), 
                    embedding=bert_dur,
                    embedding_scale=1,
                    features=ref_s, # reference from the same speaker as the embedding
                    embedding_mask_proba=0.1,
                    num_steps=num_steps
                ).squeeze(1)
            else:
                s_preds = self.sampler(
                    noise = torch.randn_like(s_trg).unsqueeze(1).to(ref_text.device), 
                    embedding=bert_dur,
                    embedding_scale=1,
                    embedding_mask_proba=0.1,
                    num_steps=num_steps
                ).squeeze(1)
            
        s_dur = s_preds[:, 128:]
        s = s_preds[:, :128]
        
        d, _ = self.model.predictor(
            d_en,
            s_dur, 
            ref_lengths, 
            torch.randn(ref_lengths.shape[0], ref_lengths.max(), 2).to(ref_text.device), 
            text_mask
        )
        
        bib = 0

        output_lengths = []
        attn_preds = []
        
        # differentiable duration modeling
        for _s2s_pred, _text_length in zip(d, ref_lengths):

            _s2s_pred_org = _s2s_pred[:_text_length, :]

            _s2s_pred = torch.sigmoid(_s2s_pred_org)
            _dur_pred = _s2s_pred.sum(axis=-1)

            l = int(torch.round(_s2s_pred.sum()).item())
            t = torch.arange(0, l).unsqueeze(0).expand((len(_s2s_pred), l)).to(ref_text.device)
            loc = torch.cumsum(_dur_pred, dim=0) - _dur_pred / 2

            h = torch.exp(-0.5 * torch.square(t - (l - loc.unsqueeze(-1))) / (self.sig)**2)

            out = torch.nn.functional.conv1d(
                _s2s_pred_org.unsqueeze(0), 
                h.unsqueeze(1), 
                padding=h.shape[-1] - 1, groups=int(_text_length)
            )[..., :l]
            attn_preds.append(F.softmax(out.squeeze(), dim=0))

            output_lengths.append(l)

        max_len = max(output_lengths)
        
        with torch.no_grad():
            t_en = self.model.text_encoder(ref_text, ref_lengths, text_mask)
            
        s2s_attn = torch.zeros(len(ref_lengths), int(ref_lengths.max()), max_len).to(ref_text.device)
        for bib in range(len(output_lengths)):
            s2s_attn[bib, :ref_lengths[bib], :output_lengths[bib]] = attn_preds[bib]

        asr_pred = t_en @ s2s_attn

        _, p_pred = self.model.predictor(
            d_en,
            s_dur, 
            ref_lengths, 
            s2s_attn, 
            text_mask
        )
        
        mel_len = max(int(min(output_lengths) / 2 - 1), self.min_len // 2)
        mel_len = min(mel_len, self.max_len // 2)
        
        # get clips
        
        en = []
        p_en = []
        sp = []
        
        F0_fakes = []
        N_fakes = []
        
        wav = []

        for bib in range(len(output_lengths)):
            mel_length_pred = output_lengths[bib]
            mel_length_gt = int(mel_input_length[bib].item() / 2)
            if mel_length_gt <= mel_len or mel_length_pred <= mel_len:
                continue

            sp.append(s_preds[bib])

            random_start = np.random.randint(0, mel_length_pred - mel_len)
            en.append(asr_pred[bib, :, random_start:random_start+mel_len])
            p_en.append(p_pred[bib, :, random_start:random_start+mel_len])

            # get ground truth clips
            random_start = np.random.randint(0, mel_length_gt - mel_len)
            y = waves[bib][(random_start * 2) * 300:((random_start+mel_len) * 2) * 300]
            wav.append(torch.from_numpy(y).to(ref_text.device))
            
            if len(wav) >= self.batch_percentage * len(waves): # prevent OOM due to longer lengths
                break

        if len(sp) < 1:
            print("No clips found")
            return None
            
        sp = torch.stack(sp)
        wav = torch.stack(wav).float()
        en = torch.stack(en)
        p_en = torch.stack(p_en)
        
        F0_fake, N_fake = self.model.predictor.F0Ntrain(p_en, sp[:, 128:])
        y_pred = self.model.decoder(en, F0_fake, N_fake, sp[:, :128])
        
        # discriminator loss
        if (iters + 1) % self.skip_update == 0:
            if np.random.randint(0, 2) == 0:
                wav = y_rec_gt_pred
                use_rec = True
            else:
                use_rec = False

            crop_size = min(wav.size(-1), y_pred.size(-1))
            if use_rec: # use reconstructed (shorter lengths), do length invariant regularization
                if wav.size(-1) > y_pred.size(-1):
                    real_GP = wav[:, : , :crop_size]
                    out_crop = self.wl.discriminator_forward(real_GP.detach().squeeze(1))
                    out_org = self.wl.discriminator_forward(wav.detach().squeeze(1))
                    loss_reg = F.l1_loss(out_crop, out_org[..., :out_crop.size(-1)])

                    if np.random.randint(0, 2) == 0:
                        d_loss = self.wl.discriminator(real_GP.detach().squeeze(1), y_pred.detach().squeeze(1)).mean()
                    else:
                        d_loss = self.wl.discriminator(wav.detach().squeeze(1), y_pred.detach().squeeze(1)).mean()
                else:
                    real_GP = y_pred[:, : , :crop_size]
                    out_crop = self.wl.discriminator_forward(real_GP.detach().squeeze(1))
                    out_org = self.wl.discriminator_forward(y_pred.detach().squeeze(1))
                    loss_reg = F.l1_loss(out_crop, out_org[..., :out_crop.size(-1)])

                    if np.random.randint(0, 2) == 0:
                        d_loss = self.wl.discriminator(wav.detach().squeeze(1), real_GP.detach().squeeze(1)).mean()
                    else:
                        d_loss = self.wl.discriminator(wav.detach().squeeze(1), y_pred.detach().squeeze(1)).mean()
                
                # regularization (ignore length variation)
                d_loss += loss_reg

                out_gt = self.wl.discriminator_forward(y_rec_gt.detach().squeeze(1))
                out_rec = self.wl.discriminator_forward(y_rec_gt_pred.detach().squeeze(1))

                # regularization (ignore reconstruction artifacts)
                d_loss += F.l1_loss(out_gt, out_rec)

            else:
                d_loss = self.wl.discriminator(wav.detach().squeeze(1), y_pred.detach().squeeze(1)).mean()
        else:
            d_loss = 0
            
        # generator loss
        gen_loss = self.wl.generator(y_pred.squeeze(1))
        
        gen_loss = gen_loss.mean()
        
        return d_loss, gen_loss, y_pred.detach().cpu().numpy()

**Comment by yl4579** [comment]
@dabsdamoon-h It’d be great if you could make a PR that fixes the squeeze issue so it allows a batch size of 1 and gradient accumulation.

**Comment by effusiveperiscope** [comment]
For me the error occurs with F0_curve when a batch has a size 1, I solved it by specifying the squeeze dimension `classifier_out.squeeze(2)` under JDCNet's forward() in `Utils/JDC/model.py` and removing `F0_real = F0_real.unsqueeze(0)` at line 403 in train_first.py. (Not sure why the unsqueeze is there considering it is not used on F0_real when the pitch extractor/decoder are used the first two times.)
