### ISSUE TITLE
Support for batch inference

### ISSUE THREAD

**Issue by devidw** [yl4579/StyleTTS2#106]
Does the current implementation allow for batch inference, is there an example / code how to do batch inference?

Thx

**Comment by yl4579** [comment]
What do you mean by batch inference? Like give a list of texts and generate speech for each?

**Comment by addytheyoung** [comment]
@yl4579 So we're new to serving TTS at scale, but does nothing like PagedAttention (from vLLM) exist for TTS? Basically just a way to go from N inference time to ~N/b? I'd find it hard to believe that the current way of processing input one by one is anywhere close to the most efficient possible for TTS.


<img width="345" alt="Screenshot 2023-11-28 at 3 28 21 PM" src="https://github.com/yl4579/StyleTTS2/assets/40842550/acc5002b-5c1c-4e83-9b62-04dbffb46263">

**Comment by yl4579** [comment]
@addytheyoung I'm not familiar with this either, I think you may have to look more at serving deep learning models at scale in general. I think this is not different from any other deep learning models.

**Comment by yl4579** [comment]
I think the current bottleneck is the LSTM in several modules (making the complex O(n)) and the PLBERT that uses 512 context length windows. This means the pretrained model can only process up to 512 tokens in parallel at a time, around 30 seconds. You will need to change the LSTM to transformers and retrain PL-BERT with longer context windows. It’s not trivial due to architecture limitations.

**Comment by yl4579** [comment]
The easiest way of course is just run the model in parallel and share the memory of the loaded model parameters if you want to use the pretrained model without changing the architecture and retrain.

**Comment by pvbhanuteja** [comment]
The current inference script for ljspeech only supports batch size of 1. 
    
    noise = torch.randn(1,1,256).to('cuda' if torch.cuda.is_available() else 'cpu')

which basically means batch size is 1. But during trainning batch size of 10 is trained by default. It would great to have infernce scipt in similar fashion.

**Comment by niranjanakella** [comment]
@yl4579 @pvbhanuteja I tried to implement the batch inference on this thing and failed at multiple bottle necks, the inference script needs to be improved or the architecture must be modified to use transformers if not this is a deadend in most usecases. 

More Important issues with this implementation: @yl4579 
1. here is a memory leak while decoding that keeps bumping up the vRAM and could potentially crash the system.
2. Doesn't support longer context windows given the limitations of PLBERT [can be managed by efficient logic to split]
3. Doesn't provide a way to get word-level timestamps, unless @yl4579  you could point me to a phoneme & alignment matrix based "**IMPLEMENTATION**" and not the issue that speaks of it again.

**Comment by smallbraineng** [comment]
What is the memory leak?
