### ISSUE TITLE
Error while trying the Colab Notebook on a non-colab machine

### ISSUE THREAD

**Issue by martinambrus** [yl4579/StyleTTS2#125]
The Colab Notebook to synthetize speech via LJSpeech works well for me on Colab. But I now tried to copy it over to a machine running jupyter notebooks and I'm getting the following error:

```
[nltk_data] Downloading package punkt to /home/user/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

177

/home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
/home/user/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/nn/modules/rnn.py:82: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "

---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
Cell In[10], line 91
     88 _ = [model[key].eval() for key in model]
     89 _ = [model[key].to(device) for key in model]
---> 91 params_whole = torch.load("Models/LJSpeech/epoch_2nd_00100.pth", map_location='cpu')
     92 params = params_whole['net']
     94 for key in model:

File ~/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/serialization.py:1028, in load(f, map_location, pickle_module, weights_only, mmap, **pickle_load_args)
   1026     except RuntimeError as e:
   1027         raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
-> 1028 return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)

File ~/mambaforge/envs/tensorml/lib/python3.11/site-packages/torch/serialization.py:1246, in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1240 if not hasattr(f, 'readinto') and (3, 8, 0) <= sys.version_info < (3, 8, 2):
   1241     raise RuntimeError(
   1242         "torch.load does not work with file-like objects that do not implement readinto on Python 3.8.0 and 3.8.1. "
   1243         f"Received object of type \"{type(f)}\". Please update to Python 3.8.2 or newer to restore this "
   1244         "functionality.")
-> 1246 magic_number = pickle_module.load(f, **pickle_load_args)
   1247 if magic_number != MAGIC_NUMBER:
   1248     raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, 'v'.
```

I already trained stage 1 on that machine and now I'm on 20th epoch of stage 2. But even with the first stage final model, I get the same error.

EDIT: I tried to load the first stage model I trained on the other machine onto Colab and the inference works. So I guess it's something with my libraries on the other machine?

**Comment by rumbleFTW** [comment]
@martinambrus  Did you fix this issue? I am still facing this same error on azure. Tried replicating the environment, but still couldn't find a fix.

**Comment by martinambrus** [comment]
> @martinambrus Did you fix this issue? I am still facing this same error on azure. Tried replicating the environment, but still couldn't find a fix.

I didn't have time to look into this yet but I did try the fine-tune Notebook to fine-tune LJSpeech model with my own WAV samples and that actually did work including the inference... I did not investigate why just yet - so maybe try that and see if it works for you

**Comment by rumbleFTW** [comment]
I have found a solution for this. This might be caused due to corrupted checkpoint files or improper cloning using git-lfs. One can simply check by comparing the sha256 sums of the `epochs_2nd_00020.pth` from their machine and the one on the colab file to confirm if this is the case. [Read more](https://stackoverflow.com/questions/33049688/what-causes-the-error-pickle-unpicklingerror-invalid-load-key)

**Comment by AlexSteveChungAlvarez** [comment]
```
sudo apt-get install git-lfs
git lfs install
git clone ...
```
worked for me!
