### ISSUE TITLE
HiFTNet in StyleTTS 2?

### ISSUE THREAD

**Issue by PleinAcces** [yl4579/StyleTTS2#127]
Hi,
In the README file you mention:

> Check our TTS work that uses HiFTNet as speech decoder for human-level speech synthesis here: https://github.com/yl4579/StyleTTS2

Is HiFTNet currently used for StyleTTS 2?
When I check the repo, I only see iSTFTNet and HifiGAN, but maybe I missed something?

**Comment by yl4579** [comment]
The iSTFTNet is the HiFTNet.
