### ISSUE TITLE
Weird sound in the beginning and in the end of audio

### ISSUE THREAD

**Issue by flipkast** [yl4579/StyleTTS2#138]
Hi, I am getting a weird sound in every generated clip most of times.

https://drive.google.com/file/d/1hjuxDqn4d5eKbMYoYynleWV3NwCXmQWD/view?usp=sharing

**Comment by yl4579** [comment]
See https://github.com/yl4579/StyleTTS2/discussions/81#discussioncomment-7732185 and the proposed solutions. I'm working on this and trying to add this feature on the finetuning code.
