### ISSUE TITLE
How to do voice cloning with StyleTTS2?

### ISSUE THREAD

**Issue by Priyanshu-hawk** [yl4579/StyleTTS2#14]
I saw amazing samples of Zero-shot speaker adaptation. How we can do that with this implementation.

Thankyou.

**Comment by yl4579** [comment]
I’m currently working on the multispeaker demo now. The code has been fixed for multispeaker training but the training on my end has not been done yet. You can either train your own model or wait for the pretrained checkpoint to be released a few days later.

**Comment by billnye2** [comment]
Really looking forward to this too, thanks!
