### ISSUE TITLE
Use XPhoneBERT instead of the provided PL-BERT checkpoints.

### ISSUE THREAD

**Issue by rumbleFTW** [yl4579/StyleTTS2#140]
Since it is mentioned that we can use XPhoneBert instead of the provided PL-BERT checkpoints for better multi-lingual inference, could you shed some light on how to load the [XphoneBert checkpoints](https://huggingface.co/vinai/xphonebert-base/tree/main) to infer using that?
Thanks!

**Comment by yl4579** [comment]
See #28 
The quality will be much worse because XPhoneBERT uses charsiug2p and is trained solely on phonemes unlike PL-BERT, so you should keep it in mind.

**Comment by rumbleFTW** [comment]
Alright, thanks for the clarification!

Actually I wanted StyleTTS2 to work in my local language. I thought it was a drop-in replacement from the readme :sweat_smile: What do you think would be my best bet? Should I train PL-BERT from scratch using my own data? If yes how many hours of data would be sufficient for yielding good results?

Thanks!

**Comment by yl4579** [comment]
I think you could either not use pre-trained PL-BERT and initialize a BERT model from scratch (like https://github.com/yl4579/StyleTTS2/issues/139#issuecomment-1849280509) or to maximize the quality you can also train your own PL-BERT. I think you can just use wikipedia as the training corpus for your language. I am currently collecting data and in the process of training multilingual PL-BERT, see #41

**Comment by rumbleFTW** [comment]
Great! Do you have a list of the languages that you're currently working on? I can help you with data of Indic languages (10+).
