### ISSUE TITLE
slmadv using differentiable duration modeling may not be helpful and even bad

### ISSUE THREAD

**Issue by liuhuang31** [yl4579/StyleTTS2#146]
I use chinese data to train and remove pl-bert mudule. It is normal until training to stage2 joint train, which train slmadv using differentiable duration. This causes the model to collapse and there are problems with the synthesized audio pronunciation.

**Comment by liuhuang31** [comment]
I use chinese data to train and remove pl-bert mudule. It is normal until training to stage2 joint train, which train slmadv using differentiable duration. This causes the model to collapse and there are problems with the synthesized audio pronunciation.

**Comment by yl4579** [comment]
Which SLM model are you using?

**Comment by liuhuang31** [comment]
microsoft/wavlm-base-plus

**Comment by yl4579** [comment]
Yes it won't work  because it's an English model. See #70

**Comment by jarred1989** [comment]
@liuhuang31 Hi, How did you handle this SLM issue? 
Also, I found that the styletts2 audio shared by you in #139  sound good, is there anything different with here?

**Comment by liuhuang31** [comment]
@jarred1989 Hi, jarred1989. For the origin code slmadv using differentiable duration modeling, i cant got a good result, its seems not helpful for me. So i not use it, and change to the normal duration modeling as before.

**Comment by jarred1989** [comment]
got it! thx
