### ISSUE TITLE
the size of tensor a (251) must match the size of tensor b (51) at non-singleton dimension 2

### ISSUE THREAD

**Issue by 11721206** [yl4579/StyleTTS2#147]
hello, when debug the code,  batch size:2 and max_len:100, i encounter the error. when I do not use the default config, (because OOM) I change the batch_size and max_len, I always encounter this error . is there recommended config for this two parameters? thanks

**Comment by zhouyong64** [comment]
I guess your code would work if you change the vocoder to 'istftnet' in config.yml. Current code doesn't work with hifigan.

**Comment by yl4579** [comment]
Are you training from scratch or finetuning?

**Comment by yl4579** [comment]
Is this solved or not?
