### ISSUE TITLE
how to generate text sequence ?

### ISSUE THREAD

**Issue by 11721206** [yl4579/StyleTTS2#148]
![image](https://github.com/yl4579/StyleTTS2/assets/19368412/04e5850b-1929-4f73-959d-266d76d97ced)
wo want to know how to generate text sequence like this ?and why change the text type not like previous phone sequences? is there advantage for this kind type text ? thanks

**Comment by lxe** [comment]
This is done using espeak-ng phonemizer

**Comment by 11721206** [comment]
> This is done using espeak-ng phonemizer

is input pinyin sequence or phoneme sequence ?

**Comment by yl4579** [comment]
@11721206 it doesn't work for Chinese. See https://github.com/yl4579/StyleTTS/issues/10
