### ISSUE TITLE
How do I change default voices?

### ISSUE THREAD

**Issue by vgybhu-oss** [yl4579/StyleTTS2#149]
I am using python on colab.

https://colab.research.google.com/drive/1Aboxqh-CM6moUWmXp6RU73CnRKUnTo-e#scrollTo=EwJFcaFmsGMb

**Comment by yl4579** [comment]
You can't because it is a single speaker model. Please use https://colab.research.google.com/github/yl4579/StyleTTS2/blob/main/Colab/StyleTTS2_Demo_LibriTTS.ipynb model instead.

**Comment by vgybhu-oss** [comment]
wow. Thank you very much!

**Comment by vgybhu-oss** [comment]
muchwow
