### ISSUE TITLE
Solutions to punctuation pause problems

### ISSUE THREAD

**Issue by bobo-paopao** [yl4579/StyleTTS2#153]
Hello, I would like to ask how you solved the issue in styletts2 where punctuation marks could not be paused normally. Because I have seen that the solution is not to use punctuation marks to separate sentences in the text part and then synthesize them separately. I would like to know what ingenious method you used? Thanks

**Comment by bobo-paopao** [comment]
The previous styletts model could not pause normally when encountering punctuation marks.

**Comment by yl4579** [comment]
I didn't do anything to specifically fix this problem. It is just learned by itself. I think a few things could have contributed to this improvement:
1. Use of PL-BERT
2. Use of SLM adversarial training
3. Use of separate prosodic style encoder
