### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by orkars** [yl4579/StyleTTS2#154]
After I fine-tune multi speaker model I couldnt manage inference. I tried checkpoints before diff_epoch('004.pth') but I am taking same error. When I trained with same dataset with all speakers labeled as '0' there is no problem, but when it is trained with multi speaker it crash with that error in below:

`
ValueError                                Traceback (most recent call last)
Cell In[55], line 6
        3 for k, path in reference_dicts.items():
        4     ref_s = compute_style(path)
----> 6     wav = inference(text, ref_s, alpha=0.3, beta=0.7, diffusion_steps=5, embedding_scale=1)
        7     rtf = (time.time() - start) / (len(wav) / 24000)
        8     print(f"RTF = {rtf:5f}")

Cell In[54], line 41
        38 duration = torch.sigmoid(duration).sum(axis=-1)
        39 pred_dur = torch.round(duration.squeeze()).clamp(min=1)
----> 41 pred_aln_trg = torch.zeros(input_lengths, int(pred_dur.sum().data))
        42 c_frame = 0
        43 for i in range(pred_aln_trg.size(0)):

ValueError: cannot convert float NaN to integer`

**Comment by yl4579** [comment]
See #101
