### ISSUE TITLE
Is It Possible to Get Word-Level Timestamps for Generated Audio?

### ISSUE THREAD

**Issue by jtschoonhoven** [yl4579/StyleTTS2#156]
Hello! Thank you for your work on this, we're excited to try our own deployment on this project.

I'm a backend SWE, but I don't have enough expertise to answer this question myself: is it possible to get timestamps for each spoken word in the output audio? This would allow us to align our input transcript with the output.

E.g. if we send StyleTTS2 the text input `"Hello, world!"` there would be some way to extract a payload like `[{"word": "Hello,", "start_ms": 123456789, "end_ms": 234567890}, {"word": "world!", "start_ms": 323456789, "end_ms": 434567890}]`

AFAICT, StyleTTS2 has a text alignment stage early in the pipeline and I'm hoping that might be made available at the end of the pipeline.

Hope this ask is clear. Thanks!

**Comment by yl4579** [comment]
You can get phoneme level duration for sure, then you can align your phonemes back to word. Since each word is usually segmented with space, you can easily know which substring of phonemes correspond to which word. To get duration of each phoneme, see https://github.com/yl4579/StyleTTS/issues/62

**Comment by alessandropettenuzzo96** [comment]
Hi @yl4579 ,

I hope you're doing well. I'm currently working on implementing word duration and start time calculations for a speech synthesis task using your model. However, I'm encountering some difficulties in ensuring the accuracy of these calculations.

I've tried your suggestion watching [yl4579/StyleTTS](https://github.com/yl4579/StyleTTS) with no accurate results.

Here's a brief overview of what I'm doing:

Duration Prediction: I'm using the model to predict token durations, and then constructing an alignment matrix (pred_aln_trg) based on these predicted durations.
Word Durations and Start Times: I'm trying to sum the durations of tokens corresponding to each word and convert these frame counts to time durations using the hop_size and samplerate.
Despite my efforts, the calculated durations and start times seem too short compared to the expected values.

Here is a snippet of my current approach:

```
hop_size=300
samplerate=24000
# Calculate word durations
word_durations = []
current_word_duration = 0
frame_counts = pred_aln_trg.sum(dim=1).cpu().numpy()
for token_index, token in enumerate(tokens[0]):
    current_word_duration += frame_counts[token_index]
    if token == 16:  # Token 16 represents a space
        word_durations.append(current_word_duration * hop_size / samplerate)
        current_word_duration = 0
if current_word_duration > 0:
    word_durations.append(current_word_duration * hop_size / samplerate)

# Calculate start times
start_times = [0]
for i in range(1, len(word_durations)):
    start_times.append(start_times[-1] + word_durations[i - 1])

print(f"Word durations (seconds): {word_durations}")
print(f"Start times (seconds): {start_times}")
```
Despite these steps, the computed durations and start times are consistently too short. Could you provide any insights or suggestions on where I might be going wrong or how to improve the accuracy of these calculations?

I appreciate your help and look forward to your response.

Best regards,
Alessandro
