### ISSUE TITLE
styletts2 inference pip package

### ISSUE THREAD

**Issue by sidharthrajaram** [yl4579/StyleTTS2#160]
Hi, big fan of the project here. I required a pip installable package of StyleTTS 2 for inference (and specifically with a fully MIT licensed stack). I went ahead and [put one together](https://pypi.org/project/styletts2/) (also under MIT license). Just thought I would let the authors and community know. Feel free to try it out too, feedback is welcome!

**Comment by yl4579** [comment]
Added to README.
