### ISSUE TITLE
Current code doesn't work with hifigan

### ISSUE THREAD

**Issue by zhouyong64** [yl4579/StyleTTS2#161]
Current code can only work when vocoder is specified to be 'istftnet'. With hifigan, it would cause errors like [https://github.com/yl4579/StyleTTS2/issues/147](url). 

I find this not easy to fix as it involves hard-coded constants in the code and it happens in different places.

**Comment by yl4579** [comment]
I think it works. The finetuning code uses hifigan as decoder and everyone could run it. Are you training from scratch and using wrong upsample rates?

**Comment by zhouyong64** [comment]
> I think it works. The finetuning code uses hifigan as decoder and everyone could run it. Are you training from scratch and using wrong upsample rates?

The error occured I'm training stage 1 from scratch. I didn't change upsample rates. When the vocoder is not hifigan, whether it's stage 1 or stage 2 or finetune, it works fine.

**Comment by yl4579** [comment]
@zhouyong64 The LibriTTS model is HifiGAN, how come it doesn't work if you could finetune it? I think you need to change the hyperparameters to make it suit HifiGAN like using this configuration instead: https://github.com/yl4579/StyleTTS2/blob/main/Configs/config_libritts.yml

What's the error you got for using hifigan as a decoder?

**Comment by zhouyong64** [comment]
> @zhouyong64 The LibriTTS model is HifiGAN, how come it doesn't work if you could finetune it? I think you need to change the hyperparameters to make it suit HifiGAN like using this configuration instead: https://github.com/yl4579/StyleTTS2/blob/main/Configs/config_libritts.yml
> 
> What's the error you got for using hifigan as a decoder?

I'm training on Chinese data. Now I see I used the wrong configurations. Thanks for help.
