### ISSUE TITLE
Noise on long sentences

### ISSUE THREAD

**Issue by antonmks** [yl4579/StyleTTS2#165]
I get this white noise thing in a second sentence of this text right after word 'attack':

The rebirth gave Ashlock an opportunity to retake control of his life as throughout his life in this new world, he had constantly felt forced into situations and compelled to react to threats as they arose.
Naturally, such a lack of independence was expected from a human mind abruptly torn from the modern world and thrust into a tree with no warning or guidance and expected to flourish in an ancient world of cultivators where impulsive youths could imbue their weapons with the fire of their souls and attack him for the slightest grievance.

If I split the long sentence into 2, there are no noise :

The rebirth gave Ashlock an opportunity to retake control of his life as throughout his life in this new world, he had constantly felt forced into situations and compelled to react to threats as they arose.
Naturally, such a lack of independence was expected from a human mind abruptly torn from the modern world and thrust into a tree with no warning or guidance and expected to flourish. In an ancient world of cultivators where impulsive youths could imbue their weapons with the fire of their souls and attack him for the slightest grievance.

Tested with default voices here : https://huggingface.co/spaces/styletts2/styletts2

**Comment by yl4579** [comment]
This is likely a problem of the huggingface space which isn't official. I don't maintain this space so I don't know what causes this problem. If you synthesize the text on the [Colab notebook](https://colab.research.google.com/github/yl4579/StyleTTS2/blob/main/Colab/StyleTTS2_Demo_LibriTTS.ipynb), there's no such problem: https://vocaroo.com/16qGeNqWRwMl

I would recommend you post an issue in the community there: https://huggingface.co/spaces/styletts2/styletts2/discussions
