### ISSUE TITLE
Using a smaller Hifigan

### ISSUE THREAD

**Issue by kmn1024** [yl4579/StyleTTS2#168]
I was wondering if it would be possible to:
1. Load pretrained StyleTTS2 LibriTTS
2. Load hifigan v3 (from https://github.com/jik876/hifi-gan/blob/master/config_v3.json)
3. Switch the StyleTTS2 hifigan with hifigan v3
4. Save the model, and create a new StyleTTS2 config with the hifigan v3 params

However, when I compare the StyleTTS2 hifigan implementation to jik876/hifi-gan, they look a bit different (for example, the StyleTTS2 impl contains novel AdaIN1d layers).

To switch StyleTTS2 LibriTTS to a smaller hifi-gan, is the best way to train the model from scratch? Are there ways to re-use pretrained check points, to reduce training time?

**Comment by yl4579** [comment]
The model was trained end to end, meaning whenever you change the architecture you’ll have to retrain the model. One way to save time is you use the design of StyleTTS to only output the melspectrogram so you can use pretrained vocoder to convert it to waveforms.
