### ISSUE TITLE
why syletts2 can get emotions？

### ISSUE THREAD

**Issue by bobo-paopao** [yl4579/StyleTTS2#17]
Hello, I want to know why syletts2 can get emotions, how does it know what emotion this sentence should have? Because I see no difference between neutral speech synthesis and multi-emotional speech synthesis in the inference code
![image](https://github.com/yl4579/StyleTTS2/assets/81943524/86f0d066-87a8-4010-a57b-c964d0d1ef66)
![image](https://github.com/yl4579/StyleTTS2/assets/81943524/22f687a7-a325-455d-adfa-d0a71c43f9e2)

**Comment by yl4579** [comment]
The emotion comes from the text. The diffusion model samples a style with the most suitable emotions according to the text. This is described in Figure 2 of the paper.

**Comment by bobo-paopao** [comment]
Does that mean that there is no way to synthesize multiple emotions in one sentence, because emotional information is always included in text information?

**Comment by yl4579** [comment]
What do you mean by multiple emotions in one sentence?

**Comment by bobo-paopao** [comment]
What I mean is whether the same text can be read with multiple emotions such as happy, sad, angry, etc., such as "StyleTTS 2 is a text-to-speech model that leverages style diffusion and adversarial training with large speech language models to achieve human- level text-to-speech synthesis. "I can read this sentence with joy and anger.

**Comment by yl4579** [comment]
Yes, see the [style transfer section of the demo page](https://styletts2.github.io/#emo) and section B.4 of the paper. The emotion depends on the style, not the text, but the style depends on the text. So the idea is you first sample a style based on happy or angry text, then use this style to read whatever sentence you want.

**Comment by bobo-paopao** [comment]
Thank you very much. I would also like to know how to specify the speaker when performing inference after multi-speaker training?

**Comment by yl4579** [comment]
You need to use the style encoder to get the speaker embedding and then you either directly use this speaker embedding (deterministic) or you feed it into the diffusion model to sample a style of this speaker (where you can also combine the original style and the sampled style based on the new text in some way) to synthesize the speech. Stay tuned for the multispeaker demo and zero-shot speaker adaptation later this week.

**Comment by bobo-paopao** [comment]
Got it, thank you！

**Comment by bobo-paopao** [comment]
By the way, what you just said is to obtain the emotional style from the text. If this emotion is used to synthesize any sentence, do we need to use the compute_style function to calculate the style vector?

**Comment by yl4579** [comment]
compute_style is just to get the speaker embedding, whether you want to use this speaker embedding or not depends on you.

**Comment by bobo-paopao** [comment]
I Got it, thank you

**Comment by melodyze-ai** [comment]
> You need to use the style encoder to get the speaker embedding and then you either directly use this speaker embedding (deterministic) or you feed it into the diffusion model to sample a style of this speaker (where you can also combine the original style and the sampled style based on the new text in some way) to synthesize the speech. Stay tuned for the multispeaker demo and zero-shot speaker adaptation later this week.

In the LibriTTS demo (Inference_LibriTTS.ipynb) I see that the reference text is a parameter to the inference but is not finally used. The variable 'ref_bert_dur' is created using the reference text but is not used. Could you please explain how this is working? @yl4579
