### ISSUE TITLE
An Error From LJspeech Dataset

### ISSUE THREAD

**Issue by YJCmote1** [yl4579/StyleTTS2#170]
In my experiment, I found that the LJsppeech-1.1 cannot be recognized by the `soundfile`.
If there's anyone meet the same situaiton? Please let me know.

soundfile.LibsndfileError: <exception str() failed>

**Comment by yl4579** [comment]
I think it’s more of an issue of soundfile than this repo. I’m not a maintainer of soundfile. I would recommend you ask it in soundfile repo or other relevant repos.

**Comment by KenWuqianghao** [comment]
> In my experiment, I found that the LJsppeech-1.1 cannot be recognized by the `soundfile`. If there's anyone meet the same situaiton? Please let me know.
> 
> soundfile.LibsndfileError: <exception str() failed>

Did you eventually figure this out? It took me days and I still can't resolve this issue
