### ISSUE TITLE
Speech-to-speech possible?

### ISSUE THREAD

**Issue by vbrydik** [yl4579/StyleTTS2#174]
Hi! First of all great repo, voice cloning works great for me.

The question is can this repository be used for speech-to-speech conversion? I.e. instead of having text as input, have an audio as input, and "convert" it to cloned voice?

Currently i have an idea of using ASR:

input_audio -> ASR -> text -> styletts -> output_audio

Can we change this hypothetical pipeline to look like this:

input_audio -> styletts -> output_audio

Thanks!

**Comment by yl4579** [comment]
Sorry for the late reply. I was quite busy recently. Are you looking for voice conversion or you are looking for speech to speech generation (like spoken dialogue or speech translation)?

**Comment by akshatgarg99** [comment]
I believe he means a speach to speech translation something like translatortron 2

**Comment by vbrydik** [comment]
something like translatortron, but I need only english. so convert a voice in an audio based some other voise, if that makes sense :)

**Comment by yl4579** [comment]
I think you may need to translate the speech using LLM, for example, and synthesize it in different languages. This is only a TTS model, not a translation model.
