### ISSUE TITLE
Train a zero-shot voice adaptation model for a different accent/language

### ISSUE THREAD

**Issue by rajdeep1337** [yl4579/StyleTTS2#179]
I want to train a zero-shot adaptation model for a different accent of english and another language. Could you please guide me how I can train such model? Thanks!

**Comment by yl4579** [comment]
I believe you just need to train the model directly in a multilingual manner, like https://github.com/yl4579/StyleTTS2/issues/139
The model is able to pick up the accent automatically, see [#95](https://github.com/yl4579/StyleTTS2/issues/95#issuecomment-1829239083) as an example.
