### ISSUE TITLE
Epoch-based loss_param values for LibriTTS

### ISSUE THREAD

**Issue by stevenhillis** [yl4579/StyleTTS2#18]
The paper describes reducing the total training epochs for stage 1 (100 -> 30) and for stage 2 (60 -> 25) when moving from LJSpeech to LibriTTS. I'm wondering about the epoch-based loss_params like TMA_epoch, diff_epoch, and joint_epoch. How were those changed for LibriTTS?

**Comment by yl4579** [comment]
I did `TMA_epoch = 5`, `diff_epoch = 5` and `joint_epoch = 10`. The basic idea is that you want the model to produce some meaningful speech before TMA, you want the model to learn some reasonable prosodic style  space before diffusion model training, and you want the diffusion model to produce reasonably good styles before joint training.
