### ISSUE TITLE
OOD data for LibriTTS-460 training?

### ISSUE THREAD

**Issue by kmn1024** [yl4579/StyleTTS2#187]
Related to https://github.com/yl4579/StyleTTS2/issues/95, if the existing OOD_data is based on LibriTTS and used during LJSpeech training, what OOD_data did you use for LibriTTS training?

**Comment by yl4579** [comment]
It was the same as LibriTTS-460, so the OOD data is the same as itself, although the speakers are different. This is because the dataset is already large enough so we don't need an extra OOD dataset (though it helps if you can get more).
