### ISSUE TITLE
Chinese data

### ISSUE THREAD

**Issue by russell-shu** [yl4579/StyleTTS2#188]
hello,
I'm going to train a Chinese model with the Aishell,how can I prepare my data?
is there a repo that I can refer to? 

thanks

**Comment by 78Alpha** [comment]
https://github.com/IIEleven11/StyleTTS2FineTune

**Comment by russell-shu** [comment]
您的来信已经收到啦，祝生活愉快~

**Comment by russell-shu** [comment]
> https://github.com/IIEleven11/StyleTTS2FineTune

thanks

**Comment by agonzalezd** [comment]
That repository is for finetuning an English dataset, not for a dataset in a different language...

We are still waiting for the code to train other languages #41

**Comment by russell-shu** [comment]
您的来信已经收到啦，祝生活愉快~

**Comment by yl4579** [comment]
You can now follow https://huggingface.co/papercup-ai/multilingual-pl-bert to finetune in other languages.

**Comment by russell-shu** [comment]
您的来信已经收到啦，祝生活愉快~
