### ISSUE TITLE
Understanding Style tts training process

### ISSUE THREAD

**Issue by SanketDhuri** [yl4579/StyleTTS2#198]
@yl4579 
I wanted to know why there are two steps of training the same model. Do they signify something? Because it is a bit confusing for me to decide whether to train the first stage or not.

please explain the purpose of each training stage

**Comment by martinambrus** [comment]
From the [paper](https://arxiv.org/pdf/2306.07691.pdf):

> It undergoes a two-stage training process: the first stage trains the acoustic modules for mel-spectrogram reconstruction, and the second trains TTS prediction modules using the fixed acoustic modules trained in the first stage.

**Comment by lucasjinreal** [comment]
@martinambrus Does stage1 can have multiple speaker data?

**Comment by martinambrus** [comment]
> [@martinambrus](https://github.com/martinambrus) Does stage1 can have multiple speaker data?

I'm not sure how exactly stage 1 works with multilingual, as I never trained such model. But I think that you actually do need multiple speaker data for both stages.

**Comment by lucasjinreal** [comment]
@martinambrus I tested trained with expresso, not finetune but training from scratch. Had two questions want to discuss:

1. the result is overall good not but so much clear than LibriTTS, is that expresso might not enough scale size?
2. I want to know for dataset that might have emotion tag, how could I encode that emotion information into prompt or something that can make model knows `how` to synthesis?

**Comment by martinambrus** [comment]
> [@martinambrus](https://github.com/martinambrus) I tested trained with expresso, not finetune but training from scratch. Had two questions want to discuss:
> 
>     1. the result is overall good not but so much clear than LibriTTS, is that expresso might not enough scale size?
> 
>     2. I want to know for dataset that might have emotion tag, how could I encode that emotion information into prompt or something that can make model knows `how` to synthesis?

Again, I've not trained multi-speaker model, only a single speaker one. So I can't answer 1.

As for 2. - this is not possible with StyleTTS2 alone. You would need to implement tone embeddings into StyleTTS2 code yourself.
