### ISSUE TITLE
Voice Quality issue using Librispeech

### ISSUE THREAD

**Issue by Anshu-Kumar-1** [yl4579/StyleTTS2#201]
Hello, I'm found difference between the generated audios from the provided demo notebook using Librispeech and the audios available on the web page. The generated audios lack naturalness compared to the ones on the demo; they seem to lack pauses and exhibit an unnatural tone.

I've tried adjusting various parameters, including diffusion steps ([15, 20, 25]), embedding scale ([1, 2]), and altering the audio speed (110%) using `duration = model.predictor.duration_proj(x) / speed`. Despite these adjustments, the issue persists. Any insights or suggestions on how to improve the generated audios to match the quality of those on the demo page would be greatly appreciated.

Generated Audio: [https://drive.google.com/file/d/1xhYaB_1jzabYbkPwt6aP3KSNDkjdwT7X/view?usp=drive_link](https://github.com/yl4579/StyleTTS/issues/url)

Thank you for your time and impressive work!

**Comment by yl4579** [comment]
The model was trained on audiobooks so it doesn't sound natural when you synthesize speech that is not audiobook narration. The quality is quite similar to the demo. If you want more natural and conversational speech, you may finetune the model on those datasets.
