### ISSUE TITLE
HELP WANTED!!!!!!!!!!!

### ISSUE THREAD

**Issue by 21sK1p** [yl4579/StyleTTS2#235]
Can we add a checkpoint to the styleTTS2 model to finetune the model from the last epoch we trained?
As I am using the free version of Colab, I can only finish my data to 5 epochs. After that, I exceeded my GPU limit, and all my data was saved in my drive, but then I had to start training it again from the start. I want to train it from my last checkpoint (last epoch trained). I asked if we could add a checkpoint to the model for the above query, just like tortoiseTTS
(I asked blackbox.ai, and it says we can, but I need clarification on it)?
cc @yl4579 @astricks @kmn1024 @eltociear @kmn1024

**Comment by godspirit00** [comment]
Just edit the config to point the pretrained model to your last checkpoint, and set `load_only_params` to false.

**Comment by 21sK1p** [comment]
> Just edit the config to point the pretrained model to your last checkpoint, and set `load_only_params` to false.

it is not working. I tried what you said, but it is not working.
@godspirit00

**Comment by Karesto** [comment]
Could you give us your config and the command you're running ?

**Comment by martinambrus** [comment]
@21sK1p if you resolved this issue, could you please close it?
