### ISSUE TITLE
iSTFTNet and LibriTTS

### ISSUE THREAD

**Issue by stevenhillis** [yl4579/StyleTTS2#24]
I'm curious if you can share any observations about using iSTFTNet with LibriTTS. The paper implies that the performance of iSTFTNet was insufficient for LibriTTS and so HiFiGAN was adopted, but I was wondering if you did any experiments with iSTFTNet and LibriTTS and what you saw.

**Comment by yl4579** [comment]
We did this in our most recent work on vocoder: https://github.com/yl4579/HiFTNet
Basically, we could achieve close-to-ground truth performance with HiFiGAN architecture on LibriTTS but not with iSTFTNet.

**Comment by stevenhillis** [comment]
Awesome, thanks for the pointer! Any particular reason for the switch from the C8C8 architecture in the paper to the C10C6 setup in this repo?

**Comment by yl4579** [comment]
Because this repo is 24 kHz while the original one is 22.5 kHz.
