### ISSUE TITLE
train_second.py: NameError: name 'mel_len_st' is not defined

### ISSUE THREAD

**Issue by effusiveperiscope** [yl4579/StyleTTS2#25]
As of pulling the code today and attempting to run train_second.py, I get the error NameError: name 'mel_len_st' is not defined @ line 364 in `train_second.py`

**Comment by yl4579** [comment]
You are totally right, sorry for the mistake. I have fixed it.

**Comment by yl4579** [comment]
You are totally right, sorry for the mistake. I have fixed it.
