### ISSUE TITLE
train_second.py question?

### ISSUE THREAD

**Issue by effusiveperiscope** [yl4579/StyleTTS2#26]
https://github.com/yl4579/StyleTTS2/blob/2f2dece35b9cad63215ae38bf991b856d1d1c063/train_second.py#L681C1-L681C32
Apologies if I am misunderstanding something, but it seems this line (681) in train_second.py starts a block that refers to `mel_input_length`, `mels`, `asr` at two indent levels, but the loop that defines these variables per batch above (line 569) starts at three indent levels--so the block at line 681 would only process the last batch in validation?

**Comment by yl4579** [comment]
Yes, that is the part to generate samples and log them on the tensorboard. The validation is already done before this.

**Comment by effusiveperiscope** [comment]
OK thanks
