### ISSUE TITLE
Can you update the Configs/config.yml file?

### ISSUE THREAD

**Issue by GUUser91** [yl4579/StyleTTS2#27]
Can you update the config.yml file so it can be used to finetune the pretrained StyleTTS 2 model on LibriTTS?

**Comment by yl4579** [comment]
There is probably more things to be done for finetuning than just changing the config. I will work on the finetuning code later. I haven't done this before myself, but theoretically it should work for high quality synthesis with just a small amount of data.

**Comment by yl4579** [comment]
I have written the finetuning script and tested it on LJSpeech with 1 hour of data and it sounds very good. The quality is very close to the model trained with 24 hours of data (full data). I will try to finetune it with even fewer data and see how well it works, and will test it on VCTK (British accent for example) see how well it can adapt to different types of dataset. It definitely works well and even better than TortoiseTTS.

**Comment by yl4579** [comment]
I have pushed the finetuning script and configuration. If you have additional questions about the script and configuration please open a new issue.
