### ISSUE TITLE
How to replace PL-BERT with XPhoneBERT?

### ISSUE THREAD

**Issue by bharathraj-v** [yl4579/StyleTTS2#28]
Hi,

I'm looking to generate Hindi audio but it was mentioned that PL-BERT doesn't work well with other languages and I either need to train a different PL-BERT or replace the module with XPhoneBERT. 

I'm having trouble understanding how I could go about replacing the module with XPhoneBERT. The repository [XPhoneBERT](https://github.com/VinAIResearch/XPhoneBERT) describes using the model through transformers but I'm unsure how I can apply that here and this [issue thread]( https://github.com/VinAIResearch/XPhoneBERT/issues/9) suggests that the pre-trained model is not publicized so, how do I go about replacing PL-BERT with XPhoneBERT here?

Thanks!

**Comment by yl4579** [comment]
Unfortunately this is not a straightforward replacement because the phoneimzer between PL-BERT and XPhoneBERT is quite different. You will have to re-train the text aligner (ASR) with the XPhoneBERT phonemizer and also prepare your data in that format, then you can replace PL-BERT with XPhoneBERT.

**Comment by yl4579** [comment]
The model is publicly available here: https://huggingface.co/vinai/xphonebert-base

**Comment by cmp-nct** [comment]
The readme made it sound like a drop in replacement ;-)

It would be nice to get a few more steps, given many people have never trained any audio type models.
It's all a bit overwhelming

**Comment by bharathraj-v** [comment]
@yl4579, According to the citations of CharsiuG2P (XPhoneBERT's phonemizer), a lot of language data (of multiple languages including Hindi) was collected through espeak-ng, which is also used by phonemizer used in PL-Bert, Is this information relevant in this case?
