### ISSUE TITLE
`g_loss` is NaN cause of model.predictor_encoder and model.decoder

### ISSUE THREAD

**Issue by xorium** [yl4579/StyleTTS2#284]
Hi! Thank you for you work!

I'm trying to run second stage training (single speaker, non-english language) and already in epoch 0, the code hits the line [set_trace()](https://github.com/yl4579/StyleTTS2/blob/main/train_second.py#L457). I checked the recommendations from [here](https://github.com/yl4579/StyleTTS2/issues/11#issuecomment-1752182626), and it seems that none of the points apply (I’m definitely using `multilingual-PL-BERT`, it’s epoch 0, I haven’t changed the code, and the training in the first stage went without any errors).

So I tried debugging the code to see the reason, and I noticed that everything starts with [model.predictor_encoder](https://github.com/yl4579/StyleTTS2/blob/main/train_second.py#L300) and [model.decoder](https://github.com/yl4579/StyleTTS2/blob/main/train_second.py#L391) returning NaN tensors with non-NaN input data.

I don't have enough knowledge to understand the cause further. 
Could you at least guide me on where I should look next? 
Thank you!

**Comment by martinambrus** [comment]
try checking this issue along with its pull request to see if it helps - https://github.com/yl4579/StyleTTS2/issues/254

**Comment by xorium** [comment]
Thank you! This really helps!

**Comment by xorium** [comment]
Thank you! This really helps!
