### ISSUE TITLE
I get a error message from trying to finetune a model

### ISSUE THREAD

**Issue by GUUser91** [yl4579/StyleTTS2#32]
>python train_finetune.py --config_path ./Configs/config_ft.yml
Some weights of the model checkpoint at microsoft/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_v', 'encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of WavLMModel were not initialized from the model checkpoint at microsoft/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'encoder.pos_conv_embed.conv.parametrizations.weight.original0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
bert loaded
bert_encoder loaded
predictor loaded
decoder loaded
text_encoder loaded
predictor_encoder loaded
style_encoder loaded
diffusion loaded
Traceback (most recent call last):
  File "/home/user/StyleTTS2/train_finetune.py", line 714, in <module>
    main()
  File "/home/user/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/StyleTTS2/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/StyleTTS2/train_finetune.py", line 211, in main
    model, optimizer, start_epoch, iters = load_checkpoint(model,  optimizer, config['pretrained_model'],
  File "/home/user/StyleTTS2/models.py", line 702, in load_checkpoint
    model[key].load_state_dict(params[key])
  File "/home/user/StyleTTS2/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MyDataParallel:
        Missing key(s) in state_dict: "module.diffusion.net.blocks.0.attention.norm.weight", "module.diffusion.net.blocks.0.attention.norm.bias", "module.diffusion.net.blocks.0.attention.norm_context.weight", "module.diffusion.net.blocks.0.attention.norm_context.bias", "module.diffusion.net.blocks.1.attention.norm.weight", "module.diffusion.net.blocks.1.attention.norm.bias", "module.diffusion.net.blocks.1.attention.norm_context.weight", "module.diffusion.net.blocks.1.attention.norm_context.bias", "module.diffusion.net.blocks.2.attention.norm.weight", "module.diffusion.net.blocks.2.attention.norm.bias", "module.diffusion.net.blocks.2.attention.norm_context.weight", "module.diffusion.net.blocks.2.attention.norm_context.bias", "module.unet.blocks.0.attention.norm.weight", "module.unet.blocks.0.attention.norm.bias", "module.unet.blocks.0.attention.norm_context.weight", "module.unet.blocks.0.attention.norm_context.bias", "module.unet.blocks.1.attention.norm.weight", "module.unet.blocks.1.attention.norm.bias", "module.unet.blocks.1.attention.norm_context.weight", "module.unet.blocks.1.attention.norm_context.bias", "module.unet.blocks.2.attention.norm.weight", "module.unet.blocks.2.attention.norm.bias", "module.unet.blocks.2.attention.norm_context.weight", "module.unet.blocks.2.attention.norm_context.bias". 
        Unexpected key(s) in state_dict: "module.diffusion.net.to_features.0.weight", "module.diffusion.net.to_features.0.bias", "module.diffusion.net.blocks.0.attention.norm.fc.weight", "module.diffusion.net.blocks.0.attention.norm.fc.bias", "module.diffusion.net.blocks.0.attention.norm_context.fc.weight", "module.diffusion.net.blocks.0.attention.norm_context.fc.bias", "module.diffusion.net.blocks.1.attention.norm.fc.weight", "module.diffusion.net.blocks.1.attention.norm.fc.bias", "module.diffusion.net.blocks.1.attention.norm_context.fc.weight", "module.diffusion.net.blocks.1.attention.norm_context.fc.bias", "module.diffusion.net.blocks.2.attention.norm.fc.weight", "module.diffusion.net.blocks.2.attention.norm.fc.bias", "module.diffusion.net.blocks.2.attention.norm_context.fc.weight", "module.diffusion.net.blocks.2.attention.norm_context.fc.bias", "module.unet.to_features.0.weight", "module.unet.to_features.0.bias", "module.unet.blocks.0.attention.norm.fc.weight", "module.unet.blocks.0.attention.norm.fc.bias", "module.unet.blocks.0.attention.norm_context.fc.weight", "module.unet.blocks.0.attention.norm_context.fc.bias", "module.unet.blocks.1.attention.norm.fc.weight", "module.unet.blocks.1.attention.norm.fc.bias", "module.unet.blocks.1.attention.norm_context.fc.weight", "module.unet.blocks.1.attention.norm_context.fc.bias", "module.unet.blocks.2.attention.norm.fc.weight", "module.unet.blocks.2.attention.norm.fc.bias", "module.unet.blocks.2.attention.norm_context.fc.weight", "module.unet.blocks.2.attention.norm_context.fc.bias".

**Comment by yl4579** [comment]
This is likely because you set multispeaker to false while the pre-trained model has multispeaker to true. You need to change this line: https://github.com/yl4579/StyleTTS2/blob/main/train_finetune.py#L211 to 
```python
        model, optimizer, start_epoch, iters = load_checkpoint(model,  optimizer, config['pretrained_model'],
                                    load_only_params=config.get('load_only_params', True), ignore_modules=['diffusion'])
```
so you don't load the parameters for diffusion models.
