### ISSUE TITLE
Laugh, Chuckle, giggling, 'Uhuh'(Nodding sound), etc

### ISSUE THREAD

**Issue by RillmentGames** [yl4579/StyleTTS2#35]
I'm wondering how to extend this excellent work to synthesize more types of expressions like in the title?

For laughs, just using the text "Haha" works, but often sounds like a fake laugh and I have no idea what text makes a giggle sound, it might not even have an IPA representations. 
I guess a better approach would be to add some [VQS](https://en.wikipedia.org/wiki/Voice_Quality_Symbols) symbols, add some appropriate training data that includes the extra VQS symbols and hack the phonemizer to allow something like "`*giggle* Thats funny!`" to be phonemized by using a custom dictionary for the giggle part and espeak for the rest. Finally, retrain the ASR with an expanded vocabulary. Is this a good approach?   

If the vocabulary expands, then would I need to retrain the ASR from scratch or can it be finetuned?

Alternatively, sampling a laughing, giggling, etc style might work but I think there would be less fine-grained speech control than expanding the vocabulary, especially if laughing and giggling appear in the same same sentence, wouldn't it?

**Comment by yl4579** [comment]
Yes, it generally works. You can reuse some IPA symbols from the ASR model (there are 178 tokens, many are not used) for these voice attributes. You can just finetune the pre-trained ASR models with your new phonemization rules (instead of re-training as you only star to use a few unused tokens).
