### ISSUE TITLE
SSML support

### ISSUE THREAD

**Issue by tyleradams** [yl4579/StyleTTS2#38]
Could you add [SSML](https://cloud.google.com/text-to-speech/docs/ssml) support, thank you!

**Comment by yl4579** [comment]
I'm not quite familiar with SSML, but it seems like some way to give more fine-grained controls like pauses and additional sounds. However, you are welcome to contribute to this feature.

**Comment by omega3** [comment]
Is this commit merged? How to use it to make pauses / breaks?
