### ISSUE TITLE
Portability? (iOS, etc.)

### ISSUE THREAD

**Issue by aehlke** [yl4579/StyleTTS2#39]
Sorry for the naive question - is there any suggested direction to porting this to iOS given that it's all Python, or would that require a completely original project?

**Comment by yl4579** [comment]
You may refer to Pytorch mobile: https://pytorch.org/mobile/ios/. This requires LibTorch, but it should be easy to encapsulate the inference function into a module, save it and call it directly using LibTorch. I have tried it with StyleTTS and it works perfectly fine (haven't tried it with StyleTTS 2 but it should be the same).
