### ISSUE TITLE
About the code of the decoder part

### ISSUE THREAD

**Issue by Superman-Valencia** [yl4579/StyleTTS2#4]
Thank you for your great work！🙂
The idea of ​​combining an encoder and a vocoder gave me great inspiration. I am trying to implement this idea now. Would you like to provide this part of the code for reference? 
Thank you again and look forward to your reply.

**Comment by yl4579** [comment]
I have invited you to the code cleaning repo where you can see unfinished problematic code. Note that only the notebooks can produce working models, the .py files aren't working at this point.

**Comment by yl4579** [comment]
Just found that you are already in the repo, what part isn't clear about the code?

**Comment by Superman-Valencia** [comment]
> Just found that you are already in the repo, what part isn't clear about the code?

Thank you very much for your reply. 
I found that the code in the module.hifigan.py file was incomplete.

**Comment by yl4579** [comment]
I haven't started HiFiGAN yet as the single speaker model isn't working for now. You can just copy-paste the HiFiGAN code and change the resblock with AdaINResBlock, like I did with iSTFTNet.

**Comment by Superman-Valencia** [comment]
> I haven't started HiFiGAN yet as the single speaker model isn't working for now. You can just copy-paste the HiFiGAN code and change the resblock with AdaINResBlock, like I did with iSTFTNet.

Thank you for your prompt reply, it is of great help to me.

**Comment by yl4579** [comment]
I’ve pushed the code for the decoder.
