### ISSUE TITLE
Finetuning for better voice cloning

### ISSUE THREAD

**Issue by fakerybakery** [yl4579/StyleTTS2#43]

**Comment by yl4579** [comment]
Could you be more specific?

**Comment by fakerybakery** [comment]
Hi @yl4579, sorry for the confusion. I was wondering if it was possible to fine tune the model on a dataset of my voice to make it sound more like me. Is this possible? Thanks!

**Comment by yl4579** [comment]
Yes, see the fine tune script and colab demo for more details.

**Comment by fakerybakery** [comment]
OK, thanks!
