### ISSUE TITLE
Emotion in voices

### ISSUE THREAD

**Issue by fakerybakery** [yl4579/StyleTTS2#44]

**Comment by yl4579** [comment]
What do you mean?

**Comment by fakerybakery** [comment]
Hi, can I have a voice sound really happy or sad like Tortoise?

**Comment by yl4579** [comment]
Yes, but you need to supply a really happy or sad reference. It won’t sound really happy or sad by itself because the dataset isn’t that emotional in general (it’s mostly audiobook readings).

**Comment by fakerybakery** [comment]
OK, thank you!
