### ISSUE TITLE
Link to pretrained weights broken

### ISSUE THREAD

**Issue by thaije** [yl4579/StyleTTS2#45]
Hello, 

Thank you for sharing your wonderful text to speech model. 

Unfortunately, when trying to download the pretrained weights the Google Drive link gives an error: 
![image](https://github.com/yl4579/StyleTTS2/assets/2978372/df839025-23fe-415f-8ca6-cd2ca3fe883a)
I get the error for both the LjSpeech and LibriTTS models.

Perhaps it is an idea to place your model including pretrained weights on a site such as [huggingface.co](https://huggingface.co/)? That way more people will be able to find and use your TTS, and it has more reliable filestorage.

**Comment by cmp-nct** [comment]
Sounds like a good idea, should be official hosted on HF.
Until that's the case, here is the LibriTTS one available:
https://huggingface.co/Bluebomber182/StyleTTS2-LibriTTS-Model-by-yl4579/tree/main/LibriTTS

**Comment by yl4579** [comment]
I have moved everything to hugginface and updated the notebooks accordingly.
