### ISSUE TITLE
(Question) Max Length and datasets

### ISSUE THREAD

**Issue by Kreevoz** [yl4579/StyleTTS2#52]
A lot of useful information is found in the other (closed) issues, but these questions come to mind.

- **How does `max_len` impact the training/finetuning process exactly?**

In the LJS dataset, there are audio files with a duration far longer than the `max_len: 400` (=5 seconds) as it is specified in the example config file. Many files are 10 seconds long and a great majority are longer than 5 seconds. They are also included in the `train_list.txt` . Was this intentional?

- **Are audiofiles truncated once the maximum number of frames is reached?**

Should the datasets be carefully edited so that audiofiles do not exceed the maximum duration set in the config file? Is there a detrimental effect on adherence to punctuation or spelling when the model only sees short or clipped speech?

- **Is there a maximum permissible length / does the architecture impose restrictions?** Could `max_len` be set to something like `1200` and thus make full use of long audio files? (Ignoring the VRAM requirements in the current DP implementation)

**Comment by yl4579** [comment]
The dataset was prepared by someone else and it has become a benchmark dataset in TTS research: https://keithito.com/LJ-Speech-Dataset/. I honestly don't know any logic behind this splitting, but this seems to be a standard already and everyone is testing their models on this dataset.

As for when `max_len` is reached, it will just clip the samples in a batch to `max_len`. For example, if the length of your batch is `[400, 300, 200, 100]`, then your batch length will be `[4, 100]` (which is the minimum of your batch size, while any sample longer than 100 will be clipped to 100 randomly. However, if you set `max_len = 80`, then you will get `[4, 80]` instead.

Yes, you can set `max_len = 1200` if you have enough RAM. The heuristics is that the larger the value the better, so the model will learn better context. This is the same as the context window in LLM training, and people have found that longer context window helps with learning.
