### ISSUE TITLE
Audio streaming

### ISSUE THREAD

**Issue by fakerybakery** [yl4579/StyleTTS2#55]
Hi,
Can we stream audio as it is being generated for longer texts?
Thank you!

**Comment by yl4579** [comment]
This is more of an engineering work here. Since each sentence can be generated much faster than its duration, you can just generate each sentence, play and generate the next while the current sentence is being generated.

**Comment by fakerybakery** [comment]
Ok, that makes sense. Thanks! Also, it’s incredible how much faster this is than Tortoise or XTTS. Thank you for brining what before was only available to companies (or released under restrictive licenses) to the open source community!
