### ISSUE TITLE
Additional requirements for README

### ISSUE THREAD

**Issue by lhl** [yl4579/StyleTTS2#6]
Saw the code released and just got a chance to poke around. Great results testing out the default inference model!

From my install, I did have a couple install notes. As mentioned in #5 , I also ran into the PLBERT error but the fix worked and that was the only code problem for inference.

For dependencies from a fresh mamba env, `nltk` and `matplotlib` need to be installed as well from the ipynb (although `matplotlib` isn't used in my Python code). I also used `soundfile` for WAV output.

The only other gotcha getting things up and running is that currently, Pytorch doesn't work with Python 3.12 (which just released and is what's installed if you just install python or pip) - 3.11 is fine w/ PyTorch nightly, although maybe 3.10 is still required for stable releases.

Oh, also, in case anyone doesn't know `pip install gdown` is great for grabbing GDrive links onto a server.

Happy to submit a PR adding these to the docs if you'd like, otherwise, just leaving a note here for anyone else getting the code up and running.

**Comment by yl4579** [comment]
Thanks for your suggestion. I have fixed the PLBERT loading issue #5 . I have also updated the dependencies. The `soundfile` will be installed if you install `librosa`.
