### ISSUE TITLE
Phonemizer Replacement

### ISSUE THREAD

**Issue by fakerybakery** [yl4579/StyleTTS2#62]
Hi, I've found several replacements for [Phonemizer](https://github.com/bootphon/phonemizer) (GPL-licensed) that are permissively licensed:

* [DeepPhonemizer](https://github.com/as-ideas/DeepPhonemizer) - Works, but the audio quality is **significantly** lower and it tends to pause a lot. MIT-licensed
* [gruut](https://github.com/rhasspy/gruut) - Looks like the best solution so far. Used by Coqui TTS (a fork of Mozilla TTS so should work). Haven't tested it yet. MIT-licensed

**Comment by yl4579** [comment]
I think it’s because DeepPhonemizer doesn’t have the stress that the model was initially trained on, while gruut has space between each phoneme (otherwise very close).

**Comment by fakerybakery** [comment]
Hmm. I tried adding Gruut to the demo but it just gave incomprehensible speech. Maybe something with the way I implemented it. I'll test it more later today.

**Comment by lexkoro** [comment]
@fakerybakery just replacing the phonemizer won't work. Will also have to retrain the model with it. 
Also coqui switched back to espeak-ng which phonemizer also uses in the backend. Reason was, gruut not providing good results compared to espeak-ng.

**Comment by yl4579** [comment]
So it seems phohemizer is here to stay. One can use some wrapper to call espeak to get around GPL limitations.

**Comment by fakerybakery** [comment]
Maybe one day someone will make a replacement for phonemizer. espeak-ng is open-sourced, but it would take quite a bit of work to reimplement it. Really wish `jonsd` had chosen LGPL instead of GPL.

**Comment by yl4579** [comment]
It would be great if you could find a way to use espeak while still maintain the current MIT license status.

**Comment by fakerybakery** [comment]
Yes, that would be great. Maybe I can try reverse-engineering espeak-ng later.

**Comment by MohannadEhabBarakat** [comment]
@fakerybakery I could help
