### ISSUE TITLE
Speed up speech

### ISSUE THREAD

**Issue by AWAS666** [yl4579/StyleTTS2#64]
Is there a way to provide a speed scaling to the model, seen that on a handful of other tts system and speaking speed can feel slow sometimes

**Comment by cmp-nct** [comment]
Just wondering, did you try provide a sample speaker who speaks faster than usual ? 

One cheap method is to increase sampling rate a bit during playback, that can sound quite natural (voice will pitch up slightly). Works both ways.
There are certainly more sophisticated methods to speed up speech without changing pitch, never tried myself though.

**Comment by yl4579** [comment]
See https://github.com/yl4579/StyleTTS/issues/3
