### ISSUE TITLE
AttributeError: module 'llvmlite.binding' has no attribute 'get_host_cpu_name'

### ISSUE THREAD

**Issue by RoneChen** [yl4579/StyleTTS2#76]
Hi, could you please tell me which version of numba and llvmlite can be used?

When I run the notebook `Inference_LibriTTS.ipynb`, it throws the error.

**Comment by yl4579** [comment]
I think this a numba and llvmlite issue, but I'm not a maintainer of these libraries so you may ask it somewhere else. The Colab works fine, so you may run the Colab and check the versions there?
