### ISSUE TITLE
Multispeaker Config

### ISSUE THREAD

**Issue by bhairavmehta95** [yl4579/StyleTTS2#8]
Hi @yl4579 thanks so much for your work.

To train multispeaker, do we just need to generate `train|val_list.txt` and change `multispeaker` to True in the config?

Any chance you could share (for example) your VCTK training script?

**Comment by yl4579** [comment]
You also need to change the decoder type to HiFiGAN and make sure the data file contains the speaker ids for the second stage training. I’m currently testing the code on LibriTTS and it seems to work for the first stage, though it’s not done yet.

The code is exactly same as single speakers, the only difference is that multispeaker models use HiFiGAN decoder and the style diffuser takes one extra speaker embedding as the input.

**Comment by yl4579** [comment]
I found a few bugs in the multispeaker settings. I have fixed them, but there might still be some other problems. I'm still testing everything so it may take another one to two weeks.

**Comment by yl4579** [comment]
I found a few other bugs in the second stage as I have finished the first stage training in evaluations. Hopefully I’ll finish the LibriTTS model by next week.

**Comment by tanishbajaj101** [comment]
say i gave it data with speaker_id 0,1,2,..n in its training. Now how would I access these speakers when making an inference
