### ISSUE TITLE
`accelerate` support for `train_finetune.py` with one GPU

### ISSUE THREAD

**Issue by yl4579** [yl4579/StyleTTS2#98]
Request per https://github.com/yl4579/StyleTTS2/issues/96#issuecomment-1828819805. Current finetuning script is quite slow because it doesn't support accelerate due to #7, but a lot of people are finetuning using a single GPU, so we don't really have to worry about DP or DDP and can directly turn to accelerate which supports mixed precision that saves time and RAM. It would be great if someone could implement this feature for a single GPU. For multi-GPU we are still trying to solve #7 .

**Comment by korakoe** [comment]
I'm doing a few tests now... but I believe I may have implemented this, following [this guide](https://huggingface.co/docs/accelerate/basic_tutorials/migration)

**Comment by korakoe** [comment]
After testing, it doesn't appear that VRAM usage drops by very much, however, training speed is _seemingly_ faster from what I'm observing. I could be missing a few things, however.

**Comment by yl4579** [comment]
@korakoe Did you do 16 bit mixed precision? Does it involve diffusion training or SLM adversarial training?

**Comment by korakoe** [comment]
> @korakoe Did you do 16 bit mixed precision? Does it involve diffusion training or SLM adversarial training?

I'm using fp16 mixed precision, Diffusion training but not SLM (due to Colab, however the implementation does work)

**Comment by korakoe** [comment]
after it jumps to 14GB it drops to 11GB, so I'm assuming that accelerate is doing some form of offloading?

**Comment by yl4579** [comment]
@korakoe I think the main concern in https://github.com/yl4579/StyleTTS2/issues/96#issuecomment-1828493779 is the speed, so if the speed is faster I guess it's fine, even if VRAM drop is not that big.
